name: generate animation

on:
  # Roda automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *" 
  
  # Permite rodar manualmente a qualquer momento
  workflow_dispatch:
  
  # Roda a cada push na branch main
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Gera a animação da cobrinha a partir do seu gráfico
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: cristianmattos
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Sobe os arquivos gerados para a branch 'output'
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: cristianmattos
          outputs: |
            # Versão Light (Original)
            dist/github-contribution-grid-snake.svg?palette=github-light
            # Versão Dark (Para quem usa tema escuro)
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
